### PR TITLE
Add smbe news item

### PR DESCRIPTION
**Pull request by hyanwong**
This puts some floating images of Wilder both in the description and the main text. They might need resizing etc, and I'm not sure if they will both work.

The css classes "float-left" and "float-right" will need defining too. Sorry @benjeffery !

### CODE REVIEW

**Comment by hyanwong** [comment]
> They might need resizing etc,

Probably the one in the description will need to be shrunk somehow.

**Comment by hyanwong** [comment]
Seems like it doesn't like the thumbnail in the description, but I guess you could add pure html: this looks quite nice when hacked into the description.

```html
<img src="https://cdn.theconversation.com/avatars/1319650/width238/file-20220217-13070-11us8fz.jpg" alt="Image of Wilder Wohns" class="float:right; margin-left:0.5em">Here is a load of text
```

**Comment by jeromekelleher** [comment]
Text LGTM - I'll won't get into the presentation layer stuff!

**Comment by benjeffery** [comment]
I'll fix up the presentation here - we need a mechanism for news images and the css. Both small things, but worth doing.

**Comment by benjeffery** [comment]
Ok I've fixed this up, will merge and promote!

**Pull request merged**
