### PR TITLE
add pyslim stable build

### PR DESCRIPTION
**Pull request by petrelharp**
Um, I think this will work? But, i don't quite remember why it was commented out..

### CODE REVIEW

**Comment by benjeffery** [comment]
The last stable tag of pyslim doesn't have the file `requirements/CI-docs/requirements.txt` so the build is failing. If you're doing a release soon I wouldn't worry, but if it will be a while then change the stable build to something that works.

**Comment by petrelharp** [comment]
Ah! I'm doing a release in the next few days, and the RTD build is failing, so wanted to set up redirects to something that works for the docs. I guess I'll change the links and set up redirects, and they'll be broken for a minute until the release comes through...

**Comment by petrelharp** [comment]
I've done a pyslim release, and this seems to be working, so I think I can merge this now? (!)

**Comment by petrelharp** [comment]
what the heck - this built fine here, but the build failed when I merged this: https://github.com/tskit-dev/tskit-site/runs/4589171739?check_suite_focus=true with 
```

  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
slim -s 23 example_sim.slim
make: slim: Command not found
make: *** [Makefile:21: prereqs] Error 127
Error: Process completed with exit code 2.
```

**Pull request merged**
