### PR TITLE
add pyslim

### LINKED ISSUE #38: add pyslim
Add pyslim to the tools powered by tree sequences.

### PR DESCRIPTION
**Pull request by petrelharp**
Closes #38.

But, what do we do to make the docs build?

Also: it's not really clear where to put pyslim - simulate? analyse?

### CODE REVIEW

**Comment by petrelharp** [comment]
Oh, right: here's building the docs: 
  https://github.com/tskit-dev/tskit-site/blob/main/.github/workflows/build-deploy.yml#L133

**Comment by petrelharp** [comment]
I had a go at the workflow - only for `latest`, since `stable` is still in RTD format? But, maybe it should work fine also?

**Comment by petrelharp** [comment]
Ah, right - I need to install SLiM for this to work. It is a conda package, but are we even using conda here? Or, maybe we need to download and build - do you mind taking a look, @benjeffery?

**Comment by benjeffery** [comment]
@petrelharp Looks like building SLiM is faster than installing conda. Doc build is failing on a new error, investigating.

**Comment by benjeffery** [comment]
@petrelharp I think the file "example_sim.trees" isn't found as the doc build is running `python_api.py` before `tutorial.md` so the file doesn't exist. I can't get this to recreate locally however. Has it shown up in the circle CI runs before?

**Comment by petrelharp** [comment]
Oh, that's funny. No, that hasn't shown up before, but makes sense. I'll do something about that.

**Comment by petrelharp** [comment]
It's working! Well, except:
- is there a way to preview the documentation?
- the "latest release" on the home page is not right:
Screenshot from 2021-06-11 16-07-32

**Comment by benjeffery** [comment]
The site build from this PR is available as an artifact from the action here: https://github.com/tskit-dev/tskit-site/actions/runs/930065652 - scroll to "artifacts".

For the release to show up correctly you need to make releases on github: https://github.com/tskit-dev/pyslim/releases currently the last 7 releases are just tags, so the latest "release" is v0.314.

**Comment by petrelharp** [comment]
Hah, thanks - I hadn't done `git push --tags`.

**Comment by petrelharp** [comment]
... and the docs build looks good! Hm, but perhaps I should try to get `stable` docs working before merging.

**Comment by petrelharp** [comment]
I'm not sure it's worth it to get the stable release docs working, as they're still the RTD theme. What do you think, @benjeffery?

**Comment by benjeffery** [comment]
> I'm not sure it's worth it to get the stable release docs working, as they're still on RTD. What do you think, @benjeffery? I guess we leave up RTD for the current docs version and have latest on tskit.dev, and switch over at the next release?

Sure, I think that's what we did for msprime.

**Comment by petrelharp** [comment]
Awesome, thanks!

**Pull request merged**
