### PR TITLE
Change the Learn page to highlight tutorials

### PR DESCRIPTION
**Pull request by hyanwong**
Pining @petrelharp - does this help with #53 ?

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by petrelharp** [comment]
Great!

**Comment by petrelharp** [comment]
I've built locally and it looks good. I'd merge this, but realized I'm not sure if there's some other procedure for tskit-site?

**Comment by hyanwong** [comment]
> Great!

Is that enough to close the linked issue @petrelharp ?

**Pull request merged**
